<Project>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <VersionPrefix>0.1.0</VersionPrefix>
    <AssemblyVersion>$(VersionPrefix).0</AssemblyVersion>
    <FileVersion>$(VersionPrefix).0</FileVersion>
    <Authors>Stephen Olesen</Authors>
    <Copyright>Copyright © 2026 Stephen Olesen</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <PathMap Condition="'$(CI)' == 'true'">$(MSBuildThisFileDirectory)=/_</PathMap>
  </PropertyGroup>
</Project>
